# Generated by Django 5.2.7 on 2025-12-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App33', '0003_role_create_level_role_delete_level_role_read_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата-час доступу')),
                ('status_code', models.IntegerField(verbose_name='Статус відповіді сервера')),
            ],
            options={
                'verbose_name': 'Журнал доступу',
                'verbose_name_plural': 'Журнали доступу',
                'ordering': ['-access_time'],
            },
        ),
    ]
