# Generated by Django 5.2.7 on 2025-11-30 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App33', '0003_role_create_level_role_delete_level_role_read_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App33.access')),
            ],
        ),
    ]
