# Generated by Django 5.2.7 on 2025-12-01 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App33', '0004_accesslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-access_datetime'], 'verbose_name': 'Журнал доступу', 'verbose_name_plural': 'Журнали доступу'},
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='access_time',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата-час доступу'),
        ),
    ]
